package info.matsumana.domain.mapper;

import info.matsumana.domain.model.Employee;
import info.matsumana.domain.model.EmployeeExample.Criteria;
import info.matsumana.domain.model.EmployeeExample.Criterion;
import info.matsumana.domain.model.EmployeeExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class EmployeeSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    public String countByExample(EmployeeExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("EMPLOYEE");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    public String deleteByExample(EmployeeExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("EMPLOYEE");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    public String insertSelective(Employee record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("EMPLOYEE");
        
        if (record.getEmployeeId() != null) {
            sql.VALUES("EMPLOYEE_ID", "#{employeeId,jdbcType=INTEGER}");
        }
        
        if (record.getEmployeeName() != null) {
            sql.VALUES("EMPLOYEE_NAME", "#{employeeName,jdbcType=VARCHAR}");
        }
        
        if (record.getHiredate() != null) {
            sql.VALUES("HIREDATE", "#{hiredate,jdbcType=DATE}");
        }
        
        if (record.getSalary() != null) {
            sql.VALUES("SALARY", "#{salary,jdbcType=DECIMAL}");
        }
        
        if (record.getVersionNo() != null) {
            sql.VALUES("VERSION_NO", "#{versionNo,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    public String selectByExample(EmployeeExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("EMPLOYEE_ID");
        } else {
            sql.SELECT("EMPLOYEE_ID");
        }
        sql.SELECT("EMPLOYEE_NAME");
        sql.SELECT("HIREDATE");
        sql.SELECT("SALARY");
        sql.SELECT("VERSION_NO");
        sql.FROM("EMPLOYEE");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Employee record = (Employee) parameter.get("record");
        EmployeeExample example = (EmployeeExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("EMPLOYEE");
        
        if (record.getEmployeeId() != null) {
            sql.SET("EMPLOYEE_ID = #{record.employeeId,jdbcType=INTEGER}");
        }
        
        if (record.getEmployeeName() != null) {
            sql.SET("EMPLOYEE_NAME = #{record.employeeName,jdbcType=VARCHAR}");
        }
        
        if (record.getHiredate() != null) {
            sql.SET("HIREDATE = #{record.hiredate,jdbcType=DATE}");
        }
        
        if (record.getSalary() != null) {
            sql.SET("SALARY = #{record.salary,jdbcType=DECIMAL}");
        }
        
        if (record.getVersionNo() != null) {
            sql.SET("VERSION_NO = #{record.versionNo,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("EMPLOYEE");
        
        sql.SET("EMPLOYEE_ID = #{record.employeeId,jdbcType=INTEGER}");
        sql.SET("EMPLOYEE_NAME = #{record.employeeName,jdbcType=VARCHAR}");
        sql.SET("HIREDATE = #{record.hiredate,jdbcType=DATE}");
        sql.SET("SALARY = #{record.salary,jdbcType=DECIMAL}");
        sql.SET("VERSION_NO = #{record.versionNo,jdbcType=INTEGER}");
        
        EmployeeExample example = (EmployeeExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    public String updateByPrimaryKeySelective(Employee record) {
        SQL sql = new SQL();
        sql.UPDATE("EMPLOYEE");
        
        if (record.getEmployeeName() != null) {
            sql.SET("EMPLOYEE_NAME = #{employeeName,jdbcType=VARCHAR}");
        }
        
        if (record.getHiredate() != null) {
            sql.SET("HIREDATE = #{hiredate,jdbcType=DATE}");
        }
        
        if (record.getSalary() != null) {
            sql.SET("SALARY = #{salary,jdbcType=DECIMAL}");
        }
        
        if (record.getVersionNo() != null) {
            sql.SET("VERSION_NO = #{versionNo,jdbcType=INTEGER}");
        }
        
        sql.WHERE("EMPLOYEE_ID = #{employeeId,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    protected void applyWhere(SQL sql, EmployeeExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}