package info.matsumana.domain.mapper;

import info.matsumana.domain.model.Employee;
import info.matsumana.domain.model.EmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    @SelectProvider(type=EmployeeSqlProvider.class, method="countByExample")
    long countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    @DeleteProvider(type=EmployeeSqlProvider.class, method="deleteByExample")
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    @Delete({
        "delete from EMPLOYEE",
        "where EMPLOYEE_ID = #{employeeId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    @Insert({
        "insert into EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, ",
        "HIREDATE, SALARY, VERSION_NO)",
        "values (#{employeeId,jdbcType=INTEGER}, #{employeeName,jdbcType=VARCHAR}, ",
        "#{hiredate,jdbcType=DATE}, #{salary,jdbcType=DECIMAL}, #{versionNo,jdbcType=INTEGER})"
    })
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    @InsertProvider(type=EmployeeSqlProvider.class, method="insertSelective")
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    @SelectProvider(type=EmployeeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="EMPLOYEE_ID", property="employeeId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="EMPLOYEE_NAME", property="employeeName", jdbcType=JdbcType.VARCHAR),
        @Result(column="HIREDATE", property="hiredate", jdbcType=JdbcType.DATE),
        @Result(column="SALARY", property="salary", jdbcType=JdbcType.DECIMAL),
        @Result(column="VERSION_NO", property="versionNo", jdbcType=JdbcType.INTEGER)
    })
    List<Employee> selectByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    @Select({
        "select",
        "EMPLOYEE_ID, EMPLOYEE_NAME, HIREDATE, SALARY, VERSION_NO",
        "from EMPLOYEE",
        "where EMPLOYEE_ID = #{employeeId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="EMPLOYEE_ID", property="employeeId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="EMPLOYEE_NAME", property="employeeName", jdbcType=JdbcType.VARCHAR),
        @Result(column="HIREDATE", property="hiredate", jdbcType=JdbcType.DATE),
        @Result(column="SALARY", property="salary", jdbcType=JdbcType.DECIMAL),
        @Result(column="VERSION_NO", property="versionNo", jdbcType=JdbcType.INTEGER)
    })
    Employee selectByPrimaryKey(Integer employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    @UpdateProvider(type=EmployeeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    @UpdateProvider(type=EmployeeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    @UpdateProvider(type=EmployeeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMPLOYEE
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    @Update({
        "update EMPLOYEE",
        "set EMPLOYEE_NAME = #{employeeName,jdbcType=VARCHAR},",
          "HIREDATE = #{hiredate,jdbcType=DATE},",
          "SALARY = #{salary,jdbcType=DECIMAL},",
          "VERSION_NO = #{versionNo,jdbcType=INTEGER}",
        "where EMPLOYEE_ID = #{employeeId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Employee record);
}