package info.matsumana.domain.model;

import java.math.BigDecimal;
import java.util.Date;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEE.EMPLOYEE_ID
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEE.EMPLOYEE_NAME
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    private String employeeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEE.HIREDATE
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    private Date hiredate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEE.SALARY
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    private BigDecimal salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEE.VERSION_NO
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    private Integer versionNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEE.EMPLOYEE_ID
     *
     * @return the value of EMPLOYEE.EMPLOYEE_ID
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEE.EMPLOYEE_ID
     *
     * @param employeeId the value for EMPLOYEE.EMPLOYEE_ID
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEE.EMPLOYEE_NAME
     *
     * @return the value of EMPLOYEE.EMPLOYEE_NAME
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEE.EMPLOYEE_NAME
     *
     * @param employeeName the value for EMPLOYEE.EMPLOYEE_NAME
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEE.HIREDATE
     *
     * @return the value of EMPLOYEE.HIREDATE
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    public Date getHiredate() {
        return hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEE.HIREDATE
     *
     * @param hiredate the value for EMPLOYEE.HIREDATE
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    public void setHiredate(Date hiredate) {
        this.hiredate = hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEE.SALARY
     *
     * @return the value of EMPLOYEE.SALARY
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    public BigDecimal getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEE.SALARY
     *
     * @param salary the value for EMPLOYEE.SALARY
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEE.VERSION_NO
     *
     * @return the value of EMPLOYEE.VERSION_NO
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    public Integer getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEE.VERSION_NO
     *
     * @param versionNo the value for EMPLOYEE.VERSION_NO
     *
     * @mbg.generated Tue Mar 07 18:47:17 CST 2017
     */
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }
}